name: 'Version'
description: 'Tags all push requests to main branch with version'
inputs:
  GH_TOKEN:
    description: 'GitHub token'
    required: true
  GH_REPOSITORY:
    description: 'GitHub repository'
    required: true
  BRANCH:
    description: 'Branch'
    required: true
outputs:
  logs:
    description: 'logs'
runs:
  using: 'node12'
  main: 'dist/index.js'